# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - standard
  - rubocop-rspec

AllCops:
  NewCops: enable

Rails:
  Enabled: true
RSpec:
  Enabled: true
RSpec/DescribeClass:
  Enabled: false
Bundler/DuplicatedGem:
  Enabled: false
